import { z } from 'zod';

export const InitiateWhepStreamSchema = z.object({
  deviceId: z
    .string()
    .min(1)
    .describe('The unique Ring device ID to establish a live WebRTC video stream with'),
  sdpOffer: z
    .string()
    .min(10)
    .describe('The standard WebRTC SDP offer string generated by the client RTCPeerConnection'),
});

export const TerminateWhepStreamSchema = z.object({
  sessionUrl: z
    .string()
    .url()
    .describe('The session control URL returned by ring_initiate_whep_stream to cleanly terminate'),
});
